# Generated by Django 6.0.2 on 2026-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PICKED_UP', 'Picked Up')], default='RECEIVED', max_length=20)),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
