# Generated by Django 5.2.11 on 2026-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('EMERGENCY', 'Emergency'), ('MAINTENANCE', 'Maintenance'), ('EVENTS', 'Events'), ('POLICIES', 'Policies')], default='GENERAL', max_length=20),
        ),
    ]
