# Generated by Django 5.2.11 on 2026-02-08 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0003_alter_lostfound_id'),
        ('users', '0002_alter_resident_id_alter_staff_id_alter_technician_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfound',
            name='claimant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to='users.resident'),
        ),
        migrations.AddField(
            model_name='lostfound',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostfound',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_found_images/'),
        ),
        migrations.AddField(
            model_name='lostfound',
            name='item_type',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], default='LOST', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostfound',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
