# Generated by Django 5.2.11 on 2026-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0004_lostfound_claimant_lostfound_claimed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfound',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
