# Generated by Django 5.2.11 on 2026-02-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
